spring:
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:9090}
      database: security

server:
  port: ${SERVER_PORT:8023}

localsystementryBaseUrl: http://localhost
localgeneratorBaseUrl: http://localhost
livesystementryBaseUrl: http://gep-dev-system-entry.gep-dev-201902.svc.cluster.local
livegeneratorBaseUrl: http://gep-dev-generator.gep-dev-201902.svc.cluster.local
localname: development
